vich_uploader:
  db_driver: orm

  mappings:
    recipes_thumbnail:
      uri_prefix: /images/recipes/thumbnail
      upload_destination: '%kernel.project_dir%/public/images/recipes/thumbnail'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_remove: true
      delete_on_update: true
      inject_on_load: false
